### ISSUE TITLE
How can I change the font size?

### ISSUE THREAD

**Issue by egkareem** [Ambusy/XeditPc#1]
Hello, thanks for the nice editor. 
I have a question:
How can I change the font size, the default is too small for me (old guy)! Is it possible to change the colors?
Thanks.

**Comment by Ambusy** [comment]
Is part of SET: set font 15
For example. Just any number is correct

Greetings,
Martin

dum., 25 apr. 2021, 17:57 egkareem ***@***.***> a scris:

**Comment by Ambusy** [comment]
About colors: not implemented, but it would not be difficult . Any idea
what and how to specify that? I have no possibility to color words however.

dum., 25 apr. 2021, 17:57 egkareem ***@***.***> a scris:

**Comment by egkareem** [comment]
Thank you for your reply.
You did not tell me about the fix for the font!

As for the colors:

Coloring applies to:

  *   Background color for a specific screen area.
  *   Font color.

There are 4 areas that require coloring:

  1.  The command area where a user may type TOP, BOTTOM, FIND "string", etc.
  2.  The numbers and command area on the left
  3.  The main editing area
  4.  The margin outside the main editing area (beyond column 80 or a user-defined margi such as 72 for COBOL developers).

Example:
https://twitter.com/bmoshix/status/1345419364141584384

Another thing, currently you allow the I prefix command to add empty lines. If the user does not fill them they disappear.
This behaviour is not practical. It woud be nice to pop a dialog box before removing the null lines.

Thanks and best of luck.
Emmad
[https://pbs.twimg.com/media/Eqvjx8wXMAcmXdx.jpg:large]<https://twitter.com/bmoshix/status/1345419364141584384>
Moshix on Twitter<https://twitter.com/bmoshix/status/1345419364141584384>
“How do I enable syntax highlighting for #REXX in #XEDIT? I probably need a list of set color commands? Yes?”
twitter.com





________________________________

**Comment by Ambusy** [comment]
``I implemented some of your ideas. Colors for linenumbers, main text area and commandline. Copy at least the files I changed today in the Release map: help.txt, system profile.rex, Change history.txt and xeditpc.exe in your installation map. 
Try the new SET COLOR ..... command to change colors and note the message on the message line to see which code needs to be changed in profile.rex to make the change permanent.

To change the behaviour of I prefix command: in the release map you'll find a J.REX (to be copied in your installation map). Does the same as I but changes the line contents, so they remain.

To view the margins I recommend to use fixed-length records and the "showeol" command to see the terminal column (press help on the xedit screen where you select the filename). Would you need the file with CrLf characters, you'll have to write a copy of the save command to create a file with variable records. To make things easier for me, when I work(ed) with cobol, I have a piece in my "profile.rex" that may serve as example after line:   if ftype.1 = "CBL"   then do

**Comment by egkareem** [comment]
Looks like you did a lot of work, I will give it a try. Thank you much.
EK

________________________________

**Comment by Ambusy** [comment]
with pleasure

**Comment by egkareem** [comment]
I found the help file and noticed the amount of work implemented. It is very very good!

You may like to consider the following:

1-CC (copy block after/before) did not work for me

2-SET COLOR COMMAND #FF0000
Works but shows an eror dialog box "Rexx program #FF0000 not found..."
As you suggested I can change the color from the profile.

3-FIND is case sensitive. I personally prefer to have a setting to control case sensitivity.

4-Scroll bar on the right hand-side is very small compared to other Windows programs, say note page.

5-Say I paste a large text in, do some work and issue some commands, type command UNDO, everything is gone....Please add a confirmation dialog (similar to QUIT)

6-Quit commands asks for confirmation. Good. However, if you close the window from (x) button at
the top right, every thing is gone...Please remove the close button at the top right of the dialog box used for confirmation.

7-It would be nice to provide a background color for the entire editing area background. 

8-It would be nice to assign ctrl-z to perform Undo like Command Z

9-It would be nice to hilight pending and wrong prefix commands with some color to indicate the state

10-The line 
     "F1=HELP F2=..."
causes the editor to show it in a .cbl file between lines 28 and 29. I expect it to be at the bottom, maybe above the 
command line. I tried to change the line number in the profile but It did not take effect.
--------------------------

Thanks again for your excellent effort.

**Comment by Ambusy** [comment]
solutions
1. CC .... CC .... P or F (indicate block to copy and line where the block is copied PREVIOUS or FOLLOWING) works for me. The command is executed by the P or F prefix command, if there are at least 2 CC prefix commands present.
2. You probably have "SET LINEND ON #" active. Thus you entered 2 commands on one line. Try set linend off. When you enter this command withou a color, a color palette is shown.
3. use SET CASE MIXED IGNORE to LOCATE something without respecting cases.
4. I know
5. Undo removes all changes from last time you pressed ENTER. Advice is to use ENTER more often without any command to define units of work
6. might be a good idea. One errs sometimes!
7. but then you don't see trailing spaces! prefer it like this. Might make it optional.
8. default it is that way. See "system profile.rex" line 13.
9. everything that is in the linenumber area is pending. after each ENTER pending commands that wait for another command reappear, the rest disappears, eventually with an error message
10. the correct solution would be an -1 or -2 to indicate "above the bottom line". I never implemented it. Will look into it. Note: if you change the profile.rex or system profile.rex, you have to restart xedit to see effects.

**Comment by egkareem** [comment]
Thank you for the quick response.
Your are correct, CC requires P or F (I though it requires (A)fter or (B)before), me bad, it has been 20+ years!

When I save the file all lines come in one line how to set new line ON in Windows?

Good work indeed.
Many thanks.

**Comment by Ambusy** [comment]
made something for 4, 6, 8 and 10.  See help file for how-to
